### ISSUE TITLE
贡献个Docker-Compose配置

### ISSUE THREAD

**Issue by Wnltc** [leesinz/Athena#2]
Dockerfile:
```
FROM python:3.8.10-slim-buster

RUN mkdir -p /app
WORKDIR /app

COPY . /app/
RUN sed -i 's/http:\/\/deb.debian.org\/debian/http:\/\/mirrors.cloud.tencent.com\/debian/g' /etc/apt/sources.list \
    && sed -i 's/http:\/\/security.debian.org\/debian-security/http:\/\/mirrors.cloud.tencent.com\/debian-security/g' /etc/apt/sources.list \
    && apt update -y \
    && apt install gcc libmariadb-dev -y \
    && pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r /app/requirements.txt

ENTRYPOINT python3 /app/main.py
```

docker-compose.yml:
```
version: "2"
services:
  db:
    image: mariadb:10.4
    container_name: athena-db
    environment:
      MYSQL_DATABASE: athena
      MYSQL_ROOT_PASSWORD: athena
      MYSQL_USER: athena
      MYSQL_PASSWORD: athena
      TZ: Asia/Shanghai
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/log:/var/log/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
    restart: always

  app:
    build: .
    image: athena-app
    container_name: athena-app
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
```
